// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQLIOy47mPKdEg1jni8LJVyrRnbfkgv9k',
    appId: '1:125165301599:web:b51d6612c370805aa190ea',
    messagingSenderId: '125165301599',
    projectId: 'mo-pay-1c8da',
    authDomain: 'mo-pay-1c8da.firebaseapp.com',
    storageBucket: 'mo-pay-1c8da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNKKEwM9cN6KaocB9QUslsQFTHerju6d0',
    appId: '1:125165301599:android:f06860c2e91245d9a190ea',
    messagingSenderId: '125165301599',
    projectId: 'mo-pay-1c8da',
    storageBucket: 'mo-pay-1c8da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjyodCCAfon5prjJKxBdx8SPjbDlBW5QM',
    appId: '1:125165301599:ios:701379797d294d38a190ea',
    messagingSenderId: '125165301599',
    projectId: 'mo-pay-1c8da',
    storageBucket: 'mo-pay-1c8da.firebasestorage.app',
    iosBundleId: 'com.example.moPay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjyodCCAfon5prjJKxBdx8SPjbDlBW5QM',
    appId: '1:125165301599:ios:701379797d294d38a190ea',
    messagingSenderId: '125165301599',
    projectId: 'mo-pay-1c8da',
    storageBucket: 'mo-pay-1c8da.firebasestorage.app',
    iosBundleId: 'com.example.moPay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQLIOy47mPKdEg1jni8LJVyrRnbfkgv9k',
    appId: '1:125165301599:web:620ae2a38aaa83a5a190ea',
    messagingSenderId: '125165301599',
    projectId: 'mo-pay-1c8da',
    authDomain: 'mo-pay-1c8da.firebaseapp.com',
    storageBucket: 'mo-pay-1c8da.firebasestorage.app',
  );

}